### ISSUE TITLE
Does `--golden-run` resolves symbolic links?

### ISSUE THREAD

**Issue by lpascal-ledger** [LedgerHQ/ragger#158]
`Ragger` has a capacity to update the currently used  snapshots with the `--golden-run` parameter.
It's very useful when the OS updates some fonts or slightly move elements: devs do not have to take all the new snapshots by hand or run the tests 1000x times to update their tests.

In the same time, it can happen that snapshots are not directly images but links to other images, to avoid duplication.
In this case, is `Ragger` able to correctly update the original images, rather than replacing the links?

**Comment by xchapron-ledger** [comment]
It doesn't, when running in `--golden-run`, this part of the code is called:
https://github.com/LedgerHQ/ragger/blob/master/src/ragger/backend/speculos.py#L206-L208

Which call this:
https://github.com/LedgerHQ/ragger/blob/master/src/ragger/backend/speculos.py#L189-L192

Which will replace the link with the new snapshot.
We could probably add some logic on the _save_screen_snapshot() function to check if the existing file is a link, and if so replace the link target.

**Comment by lpascal-ledger** [comment]
I've been using the `--golden_run` feature extensively for the MISC porting, it turns out that the link are correctly resolved and the pointed images correctly updated.
This must be directly resolved at a system level: if you `cp` a file on a link, it is the link destination which is updated.

I guess this issue is resolved then.
